version: '3.4'

services:
  reverseproxy:
    container_name: nginx-proxy
    image: docker.io/nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always

  nginx:
    container_name: nginx-web-server
    depends_on:
      - reverseproxy
    image: nginx:alpine
    restart: always

  apache:
    container_name: apache-web-server
    depends_on:
      - reverseproxy
    image: httpd:alpine
    restart: always

  grafana:
    container_name: grafana
    depends_on:
      - reverseproxy
    image: grafana/grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_DOMAIN=localhost